version: "3"
services:
  app:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/mongoapi
    ports:
      - "3000:3000"
    environment:
       - MONGO_DB_USER=pokemon
       - MONGO_DB_PASS=123
